[UP][TECH-444]Post Sign Up Flow
IBS-Skillset/my-stays-ui pull request #14
Opened 2022-09-29 13:55 UTC by akhil-v-011

2022-09-30 10:43 UTC, JeanMariaJose requested changes

2022-09-30 10:43 UTC, JeanMariaJose commented on src/actions/signUpAction.ts
> +}
Have you tried this with backend service. When you do a create account the details should get entered in DB in Create Account service and verify if the details are present in H2 DB and see the email is auto populated. You need to remove the hardcoded portions if any

2022-10-04 07:42 UTC, JeanMariaJose approved these changes

2022-10-04 07:49 UTC, JeanMariaJose requested changes

2022-10-04 07:49 UTC, JeanMariaJose commented on src/reducers/signupReducer.ts
> +}
pls rebase your branch with main

2022-10-07 05:04 UTC, JeanMariaJose submitted a review, later dismissed

2022-10-10 11:04 UTC, abhijithramankutty commented on src/pages/sign-up/SignUp.tsx
> +            : dispatch(autoPopulateEmail(''))
is it really needed to have a dispatch action with empty data ?

2022-10-10 11:04 UTC, abhijithramankutty commented on src/actions/signUpAction.ts
> +export function autoPopulateEmail(email: string): ActionSignup | AnyAction {
Action function name can be append with "Action" for better readability. i.e. can be rename this to `autoPopulateEmailAction`

2022-10-11 10:37 UTC, abhijithramankutty approved these changes

2022-10-11 10:37 UTC, merged