TECH-417 SignUp page
IBS-Skillset/my-stays-ui pull request #4
Opened 2022-08-18 06:16 UTC by PoornaPanda9785

2022-08-18 06:33 UTC, JeanMariaJose commented on src/pages/sign-up/SignUp.tsx
> +          console.log(values)
when you log pass word , it should be encrypted

2022-08-18 07:44 UTC, abinthomas258 commented on src/pages/sign-up/SignUp.tsx
> +                className="block text-black text-sm font-semibold mb-2"
'block text-black text-sm font-semibold mb-2' * 5 times in the same file can be given as a combined CSS class using @apply annotation

2022-08-18 08:19 UTC, abinthomas258 requested changes
- Compare React Hook Form vs Formik
- use @apply for reusing CSS class

2022-08-18 08:19 UTC, abinthomas258 commented on package.json
> +    "formik": "^2.2.9",
Just analyze and compare if we can use React Hook Form over Formik. 

It appears that React Hook Form has frequent updates over Formik which have last published one year ago.

found some useful blogs on the internet

React Hook Form isolates input components from the others and prevents re-render the form for a single input. It avoids this unnecessary re-rendering. So it is a great advantage in terms of performance compared to Formik which updates every change in every input field

2022-08-23 05:23 UTC, merged

2023-05-12 07:38 UTC, kalarikkalbabu commented
The tests have failed. Please check the logs and fix the issues.